// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

[TestFixture]
public class AdditiontestTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void additiontest() {
    driver.Navigate().GoToUrl("https://www.calculatorsoup.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(2064, 1127);
    driver.FindElement(By.Name("cs_one")).Click();
    driver.FindElement(By.Name("cs_zero")).Click();
    driver.FindElement(By.Name("cs_add")).Click();
    driver.FindElement(By.Name("cs_five")).Click();
    driver.FindElement(By.Name("cs_equal")).Click();
  }
}
